services:

  mongodb:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - mongo_data:/data/db

  datanode:
    image: graylog/graylog-datanode:${GRAYLOG_VERSION}
    hostname: "datanode"
    depends_on:
      - mongodb
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    volumes:
      - graylog_datanode:/var/lib/graylog-datanode

  graylog:
    image: graylog/graylog:${GRAYLOG_VERSION}
    hostname: "server"
    depends_on:
      - datanode
      - mailcatcher
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://${GRAYLOG_HOST}:${GRAYLOG_PORT}/
      - GRAYLOG_ROOT_TIMEZONE=Europe/Madrid
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/data/node-id
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    ports:
      # Graylog web interface and REST API
      - "${GRAYLOG_PORT}:9000"
      # Syslog
      - "514:514"
      - "514:514/udp"
      # GELF
      - "12201:12201"
      - "12201:12201/udp"
    volumes:
      - graylog_data:/usr/share/graylog/data/data
      - graylog_journal:/usr/share/graylog/data/journal

  mailcatcher:
    image: stpaquet/alpinemailcatcher:${MAILCATCHER_VERSION:-latest}
    ports:
      - "${MAILCATCHER_PORT}:1080"

volumes:
  mongo_data:
  graylog_datanode:
  graylog_data:
  graylog_journal:
