version: "3.5"

services:

  https-portal:
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION:-1}
    environment:
      DOMAINS: >
        graylog.test -> http://graylog:9000
      CLIENT_MAX_BODY_SIZE: 128M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
      - https-portal_logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - graylog
    networks:
      - graylog

  mongo:
    image: mongo:5.0.13
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog

  graylog:
    image: graylog/graylog:5.0
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=1234567890abcdef
      # Password: 12345Abcde
      - GRAYLOG_ROOT_PASSWORD_SHA2=900563a48c044074dc467feac110df09372301dbc10968c2c4491ad2398c93e6
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ROOT_TIMEZONE=Europe/Madrid
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    expose:
      # Graylog web interface and REST API
      - 9000
      # Syslog TCP
      - 1514
      # Syslog UDP
      - 1514/udp
      # GELF TCP
      - 12201
      # GELF UDP
      - 12201/udp

networks:
  graylog:

volumes:
  mongo_data:
  es_data:
  graylog_journal:
  https-portal_certs:
  https-portal_logs:
